api/urls.py
from django.urls import path

from .views import bbs, BbDetailView, comments

app_name = 'api'

urlpatterns = [
    path('bbs/<int:pk>/comments/', comments),
    path('bbs/<int:pk>/', BbDetailView.as_view()),
    path('bbs/', bbs),
]

bboard/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.views import serve
from django.views.decorators.cache import never_cache
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('captcha/', include('captcha.urls')),

    path('api/', include('api.urls')),
    path('', include('main.urls'))
]

if settings.DEBUG:
    urlpatterns.append(path('static/<path:path>', never_cache(serve)))
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path

from .views import (index, other_page, BbLoginView, profile, BbLogoutView,
                    ChangeUserInfoView, BbPasswordChangeView,
                    RegisterDoneView, RegisterUserView, user_activate,
                    DeleteUserView, by_rubric, detail, profile_bb_detail,
                    profile_bb_add, profile_bb_change, profile_bb_delete)

app_name = 'main'

urlpatterns = [
    path('<int:rubric_pk>/<int:pk>/', detail, name='detail'),
    path('<int:pk>/', by_rubric, name='by_rubric'),
    path('<str:page>', other_page, name='other'),
    path('', index, name='index'),

    path('accounts/register/activate/<str:sign>/', user_activate, name='register_activate'),
    path('accounts/register/done/', RegisterDoneView.as_view(), name='register_done'),
    path('accounts/register/', RegisterUserView.as_view(), name='register'),
    path('accounts/login/', BbLoginView.as_view(), name='login'),

    path('accounts/profile/change/', ChangeUserInfoView.as_view(), name='profile_change'),

    path('accounts/profile/change/<int:pk>/', profile_bb_change, name='profile_bb_change'),
    path('accounts/profile/delete/<int:pk>/', profile_bb_delete, name='profile_bb_delete'),
    path('accounts/profile/add/', profile_bb_add, name='profile_bb_add'),
    path('accounts/profile/<int:pk>/', profile_bb_detail, name='profile_bb_detail'),
    path('accounts/profile/', profile, name='profile'),

    path('accounts/logout/', BbLogoutView.as_view(), name='logout'),
    path('accounts/password/delete/', DeleteUserView.as_view(), name='profile_delete'),
    path('accounts/password/change/', BbPasswordChangeView.as_view(), name='password_change'),
]

templates/layout/basic.html
{% load bootstrap4 %}
{% load static %}

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}Главная{% endblock %} – Доска объявлений</title>
    {% bootstrap_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'main/style.css' %}">
    {% bootstrap_javascript jquery='slim' %}
</head>
<body class="container-fluid">
    <header class="mb-4 bg-primary text-white py-3">
        <h1 class="display-4 text-center">Объявления</h1>
    </header>
    <div class="row mb-3">
        <ul class="col nav justify-content-end border-bottom py-2">
            <li class="nav-item"><a class="nav-link text-primary" href="{% url 'main:register' %}">Регистрация</a></li>
            {% if user.is_authenticated %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle text-primary"
                       data-toggle="dropdown"
                       href="#" role="button" aria-haspopup="true"
                       aria-expanded="false">Профиль</a>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" href="{% url 'main:profile' %}">Мои объявления</a>
                        <a class="dropdown-item" href="{% url 'main:profile_change' %}">Изменить личные данные</a>
                        <a class="dropdown-item" href="{% url 'main:password_change' %}">Изменить пароль</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'main:logout' %}">Выйти</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item text-danger" href="{% url 'main:profile_delete' %}">Удалить</a>
                    </div>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link text-primary" href="{% url 'main:login' %}">Вход</a>
                </li>
            {% endif %}
        </ul>
    </div>
    <div class="row">
        <nav class="col-md-3 nav flex-column bg-light border-right py-3">
            <a class="nav-link root text-dark font-weight-bold" href="{% url 'main:index' %}">Главная</a>

            {% for rubric in rubrics %}
                {% ifchanged rubric.super_rubric.pk %}
                    <span class="nav-link root text-dark font-weight-bold">
                        {{ rubric.super_rubric.name }}</span>
                {% endifchanged %}
                <a class="nav-link text-secondary" href="{% url 'main:by_rubric' pk=rubric.pk %}">
                    {{ rubric.name }}</a>
            {% endfor %}

            <a class="nav-link root text-dark font-weight-bold" href="{% url 'main:other' page='about' %}">О сайте</a>
        </nav>
        <section class="col-md-9 py-3">
            {% bootstrap_messages %}
            {% block content %}
            {% endblock %}
        </section>
    </div>
    <footer class="text-center bg-dark text-white py-3 mt-3">
        <p class="mb-0">&copy; {{ current_year }} читатели. Все права защищены.</p>
    </footer>
</body>
</html>